package argument

const (
	APIKey = "api_key"
	CategoryId = "category_id"
	RealTimeStart = "realtime_start"
	RealTimeEnd = "realtime_end"
	Limit = "limit"
	Offset = "offset"
	OrderBy = "order_by"
	SortOrder = "sort_order"
	FilterVariable = "filter_variable"
	FilterValue = "filter_value"
	TagNames = "tag_names"
	ExcludeTagNames = "exclude_tag_names"
	TagGroupId = "tag_group_id"
	SearchText = "search_text"
	IncludeReleaseDatesWithNoData = "include_release_dates_with_no_data"
	ReleaseId = "release_id"
	ElementId = "element_id"
	IncludeObservationValues = "include_observation_values"
	ObservationDate = "observation_date"
	SeriesId = "series_id"
	ObservationStart = "observation_start"
	ObservationEnd = "observation_end"
	Units = "units"
	Frequency = "frequency"
	AggregationMethod = "aggregation_method"
	OutputType = "output_type"
	VintageDates = "vintage_dates"
	TagSearchText = "tag_search_text"
	SeriesSearchText = "series_search_text"
	SourceId = "source_id"
)